<a href="https://colab.research.google.com/github/skyil7/SejongUniv_ML/blob/master/3.Linear%20Regression%20And%20Regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 선형 회귀와 규제 실습
- 와인 데이터셋 활용

In [9]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
data.head()
data.columns = ['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline'] 
print('class label:', np.unique(data['class label']))
data.head()

class label: [1 2 3]


class label  alchohol  malic acid  ...   hue  OD208  proline
0            1     14.23        1.71  ...  1.04   3.92     1065
1            1     13.20        1.78  ...  1.05   3.40     1050
2            1     13.16        2.36  ...  1.03   3.17     1185
3            1     14.37        1.95  ...  0.86   3.45     1480
4            1     13.24        2.59  ...  1.04   2.93      735

[5 rows x 14 columns]

## data pre_processing

In [3]:
from sklearn.model_selection import train_test_split
X, y = data.iloc[:,1:].values, data.iloc[:,0].values
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

# Regularization에 따른 정확도 확인하기
- C가 작을수록 규제가 심해짐

In [11]:
from sklearn.linear_model import LogisticRegression
lr2_10 = LogisticRegression(penalty='l2', C=10.0, solver='saga')  # L2 with C(=1/λ)=10
lr2_1 = LogisticRegression(penalty='l2', C=1.0, solver='saga')    # L2 with C(=1/λ)=1
lr2_0_1 = LogisticRegression(penalty='l2', C=0.1, solver='saga')  # L2 with C(=1/λ)=0.1

lr1_10 = LogisticRegression(penalty='l1', C=10.0, solver='saga')  # L1 with C(=1/λ)=10
lr1_1 = LogisticRegression(penalty='l1', C=1.0, solver='saga')    # L1 with C(=1/λ)=1
lr1_0_1 = LogisticRegression(penalty='l1', C=0.1, solver='saga')  # L1 with C(=1/λ)=0.1

In [12]:
lr2_10.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=0.1:', lr2_10.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=0.1:', lr2_10.score(X_test_std, y_test))

lr2_1.fit(X_train_std, y_train)  # warning..
print('Training accuracy with L2 and λ=1:', lr2_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=1:', lr2_1.score(X_test_std, y_test))

lr2_0_1.fit(X_train_std, y_train)
print('Training accuracy with L2 and λ=10:', lr2_0_1.score(X_train_std, y_train))
print('Test accuracy with L2 and λ=10:', lr2_0_1.score(X_test_std, y_test))

lr1_10.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=0.1:', lr1_10.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=0.1:', lr1_10.score(X_test_std, y_test))

lr1_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=1:', lr1_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=1:', lr1_1.score(X_test_std, y_test))

lr1_0_1.fit(X_train_std, y_train)
print('Training accuracy with L1 and λ=10:', lr1_0_1.score(X_train_std, y_train))
print('Test accuracy with L1 and λ=10:', lr1_0_1.score(X_test_std, y_test))

Training accuracy with L2 and λ=0.1: 1.0
Test accuracy with L2 and λ=0.1: 0.9814814814814815
Training accuracy with L2 and λ=1: 1.0
Test accuracy with L2 and λ=1: 0.9814814814814815
Training accuracy with L2 and λ=10: 1.0
Test accuracy with L2 and λ=10: 1.0
Training accuracy with L1 and λ=0.1: 1.0
Test accuracy with L1 and λ=0.1: 0.9814814814814815
Training accuracy with L1 and λ=1: 1.0
Test accuracy with L1 and λ=1: 0.9814814814814815
Training accuracy with L1 and λ=10: 0.967741935483871
Test accuracy with L1 and λ=10: 0.9444444444444444


# 규제 강도에 따른 매게 변수의 값 관찰
- 강도가 강해질 수록 값이 작아짐
- L1의 경우, 아예 0이 되기도

In [13]:
print(lr2_10.intercept_)
print(lr2_1.intercept_)
print(lr2_0_1.intercept_)

print(lr2_10.coef_)
print(lr2_1.coef_)
print(lr2_0_1.coef_)

[ 0.30609095  0.62846365 -0.9345546 ]
[ 0.28296402  0.60335303 -0.88631705]
[ 0.06848176  0.45689385 -0.52537561]
[[ 1.19141952  0.20200337  0.38722712 -1.54071047  0.0988042   0.43988475
   0.83682327 -0.29862952  0.03283865  0.16034137  0.11782758  0.9774179
   1.38272307]
 [-1.5290524  -0.46602547 -1.26180582  1.23909252 -0.31359954 -0.56665493
   0.86153215  0.41958446  0.41827685 -1.33647383  1.11068416  0.06491721
  -1.76262724]
 [ 0.33763288  0.2640221   0.87457871  0.30161795  0.21479534  0.12677019
  -1.69835543 -0.12095494 -0.4511155   1.17613246 -1.22851173 -1.04233511
   0.37990417]]
[[ 0.75487462  0.06157388  0.23345996 -0.89239796  0.02637696  0.29393399
   0.56118395 -0.20717659  0.13429359  0.12765445  0.10202973  0.61777589
   0.9095086 ]
 [-0.98660029 -0.32324277 -0.65162521  0.66769215 -0.22947253 -0.2071032
   0.43811294  0.19842724  0.24399188 -0.78017088  0.6372139   0.08567318
  -1.03444624]
 [ 0.23172567  0.26166889  0.41816525  0.22470581  0.20309557 -0.0868307

In [14]:
print(lr1_10.intercept_)
print(lr1_1.intercept_)
print(lr1_0_1.intercept_)

print(lr1_10.coef_)
print(lr1_1.coef_)
print(lr1_0_1.coef_)

[ 0.35744854  0.62320337 -0.98065191]
[ 0.28834214  0.5417377  -0.83007984]
[ 0.05083546  0.30693262 -0.35776808]
[[ 1.23635776  0.          0.16295148 -1.66257705  0.          0.33526561
   0.65581063  0.          0.          0.          0.          0.99957727
   1.41617827]
 [-1.7931647  -0.42846319 -1.45874173  1.07414192 -0.33827852 -0.46391295
   0.75476091  0.46489025  0.16650559 -1.47477235  1.07012423  0.
  -1.97888027]
 [ 0.0298203   0.15878502  0.76880362  0.06093802  0.11193334  0.
  -1.93645213  0.         -0.45372644  1.16782064 -1.25167688 -0.99550382
   0.03648109]]
[[ 0.03121453  0.          0.         -1.18818759  0.          0.
   0.01830739  0.          0.          0.          0.          0.63675786
   0.95672852]
 [-1.57822443 -0.14372964 -0.76760063  0.03319793 -0.07373118  0.
   0.          0.1253794   0.         -1.02010275  0.22610998  0.
  -1.22637675]
 [ 0.          0.          0.          0.          0.          0.
  -2.06849173  0.         -0.0531738   0.238